### ISSUE TITLE
'geom' must be either a string or a Geom object, not a base object of typeenvironment 

### ISSUE THREAD

**Issue by ooudh-nat** [wtesto/SpeciesOccurrenceMapping#1]
Hi Wtesto, 

Firstly, thank you for sharing this code, and for explaining the different aspects so well.

I have been attempting to apply this code to plot suitability weighted centroids from SDMs, however for the last section ('making the map') I have consistently been receiving the error "'geom' must be either a string or a Geom object, not a base object of typeenvironment'. Backtracing this error seems to identify the first line of geom_sf as the issue (see below), however it remains unchanged for your code. I was wondering why this occurring.  

Backtrace:
    x
 1. \-ggplot2::geom_tile(...)
 2.   \-ggplot2::layer(...)
 3.     \-ggplot2:::check_subclass(geom, "Geom", env = parent.frame())

If you have any questions, don't hesitate to ask.

Thank you

**Comment by wtesto** [comment]
Hi there, 

It is a little bit difficult to diagnose without more information on the data you are working with, but my first guess is that the centroids that you are trying to map are in an object that is not a Simple Features ('sf') object, and therefore geom_sf is not the appropriate geom for it. 

Assuming for a minute that the name of your centroid object is 'X', what does class(X) return? 

That should be a helpful first step in sorting this out. 

Wes

**Comment by ooudh-nat** [comment]
Yes, this is slightly embarrassing, a quick fix has sorted it. 
Thank you for the reply, map looks good.
